name             'ee-confluence'
maintainer       'Earth Economics'
maintainer_email 'jgerrish@eartheconomics.org'
license          'All rights reserved'
description      'Installs/Configures Atlassian Confluence'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          "apt"
depends          'users'
depends          'java'
depends          'apache2'
depends          'database'
depends          'mysql'
depends          'application'
depends          'confluence'
depends          'logrotate'
